アップデート案内が毎回出ないよう変更
TaneAkashi/DakokuApp pull request #103
Opened 2021-05-30 07:58 UTC by zeek0x

fix: #92 

リリースに対して、アプリのライフサイクル毎に１回の通知が出ます。
アプリを再起動すると、同じリリースに対して再度通知が行われます。

2021-06-09 07:45 UTC, amotarao commented on src/store.ts
> +  latest: StoreRelease;
release のままで問題ない気がしますがいかがでしょうか。

2021-06-09 07:46 UTC, amotarao commented on src/store.ts
> +  return store.get('latest');
latest が store にない状態で この関数を叩かない可能性もないと思います。
ない場合は null を返すコードは残してもいいと思います

2021-06-09 07:47 UTC, amotarao requested changes
遅くなりましたがコメントしました。

2021-06-10 17:12 UTC, zeek0x commented
@amotarao 現状の通知タイミングは

- 起動後に latest 取得後
- 打刻実行後 latest 取得後

となっていて、kvs 使わなくていいことに気づきました...。（）

これに従って

- store で release を扱わないようにし、永続的なリリース情報の保存をやめる
- release のグローバルな変数にリリース情報を保存する

のように改修したいと思うのですが、どうでしょうか？

2021-06-11 14:03 UTC, amotarao commented
@zeek0x よさそうです 👍

2021-06-12 05:09 UTC, amotarao commented on src/main.ts
> +  release.doIfNotLatest();
```suggestion
  await release.doIfNotLatest();
```

2021-06-12 05:09 UTC, amotarao approved these changes
await のとこ以外 LGTM〜〜 💯

2021-06-12 05:20 UTC, zeek0x commented on src/main.ts
> +  release.doIfNotLatest();
非同期のほうが早く whenReady 完了できていいのかなと思ってましたが、別にいいのか

2021-06-12 05:24 UTC, merged