打刻中は打刻メニューを disabled に設定するよう変更
TaneAkashi/DakokuApp pull request #117
Opened 2021-06-08 14:15 UTC by zeek0x

fix: #114

2021-06-09 07:53 UTC, amotarao requested changes
見た目もdisableにしたいです。

あと tuple 使いがちですけど どんなもんなんですかね。
可読性落ちると思いますし、そこまでスピードが求められるようなアプリでもないと思います
tuple しか使えないような言語でもないので、使わなくていいと思います

```js
['hoge', 'fuga']
  // ↓
{ title: 'hoge', body: 'fuga' }
```

2021-06-09 07:58 UTC, amotarao commented
Tuple、それぞれの内容の理解にコメントを見る必要がありますよね。

```js
const a = ['hoge', 'fuga']
const b = { title: 'hoge', body: 'fuga' }
```

それぞれで body を取り出して下さい、となったら `a[1]` / `b.body` のどちらがよいでしょうか。

また別の要素が加わったり減ったりするとき、


```js
const a = ['hoge', 'hage', 'fuga']
const b = { title: 'hoge', head: 'hage', body: 'fuga' }
```

body は `a[2]` / `b.body` と、tuple はキーを変える必要があります

2021-06-10 16:47 UTC, zeek0x commented
変数のスコープがちっちゃい時には、オブジェクトで書くのがめんどくさくてタプルで書いてますね。
半分くらいは趣味なので、わかりにくければやめます。

2021-06-10 16:52 UTC, zeek0x commented
`enalbed` プロパティへの代入で、見た目も変わるようです。
https://www.electronjs.org/docs/api/menu-item#new-menuitemoptions
> enabled Boolean (optional) - If false, the menu item will be greyed out and unclickable.

2021-06-12 05:15 UTC, amotarao commented on src/tray.ts
> +  });
ここらへんもうちょっとうまくできそうな気がしますが 思いつかない

2021-06-12 05:15 UTC, amotarao approved these changes
LGTM〜

2021-06-12 05:22 UTC, zeek0x commented on src/tray.ts
> +  });
showのbooleanも合わせて、うまいこと書き直したいですね。
別リファクタで頑張りまそ

2021-06-12 05:25 UTC, merged