feat: バージョン情報を確認できるページを追加
TaneAkashi/DakokuApp pull request #130
Opened 2021-06-15 16:21 UTC by zeek0x

fix: #110

2021-06-17 14:07 UTC, zeek0x commented
About Akashi いらないな

2021-06-17 14:22 UTC, amotarao requested changes
https://github.com/rhysd/electron-about-window
こういう系のやつでよさそうな気がします

2021-06-17 14:25 UTC, amotarao commented
有名所のElectron製アプリがどうなっているかを先に見ておきたいです

2021-06-18 14:05 UTC, zeek0x commented
他に何か表示を追加した方がいいですかね？

2021-06-18 16:57 UTC, amotarao commented on src/tray.ts
> +const trayIcon = getIconResourcePath('img/TrayIconTemplate.png');
img/ を getIconResourcePath 内に入れたい気がします

2021-06-18 16:59 UTC, amotarao commented on src/tray.ts
> +  const aboutDakokuApp = generateMenuItem('normal', 'About DakokuApp', () => {
他が日本語なので 「DakokuApp について」ですかね
```suggestion
  const aboutDakokuApp = generateMenuItem('normal', 'DakokuApp について', () => {
```

2021-06-18 17:00 UTC, amotarao requested changes
ログイン・設定ウィンドウのヘルプからも開けるようになっていたいです

2021-06-19 15:21 UTC, zeek0x commented
@amotarao ヘルプというのはこのことを指していますか？
<img width="375" alt="スクリーンショット 2021-06-20 0 20 23" src="https://user-images.githubusercontent.com/12657833/122647068-5ef1ca00-d15d-11eb-8a7f-234c8833ca6d.png">

2021-06-19 15:21 UTC, amotarao commented
そうですね。

2021-06-19 15:22 UTC, zeek0x commented on src/tray.ts
> +const trayIcon = getIconResourcePath('img/TrayIconTemplate.png');
img/ だけ入れるのは中途半端気がするんですよね
少し考えます。

2021-06-19 15:23 UTC, zeek0x commented
本当に欲しいですか？

2021-06-19 16:01 UTC, zeek0x commented
@amotarao つけるとしても Menu のをいじるので別PRにしたいです。

2021-06-19 16:15 UTC, amotarao commented
本当に欲しいですか？とかそういう次元の話じゃなくて
OSごとのアプリの差をよく観察してみてください。

2021-06-19 16:20 UTC, amotarao commented
MacOSのVSCodeとWindowsのVSCode、どこからバージョン情報が確認でき、どこからたどり着けるのか、どういうメニュー名なのか。
Chromeはどうなのか、Slackはどうなのか、
観察し比較すれば答えが出てくるはずです。

ただ単に画面追加すればええやろ的なノリでやるものではないと思います。

2021-06-19 17:40 UTC, zeek0x commented
@amotarao 観察し比較すると答えが出てきました。:mag: :bar_chart: 💯 
Aboutページは、Menu にあるべきですね。
加えて、同じ理由で  `ログイン・設定` ・ `終了` も Menu に含まれているべきですね。

このPRでは一旦 tray に追加し、別PRで Menu にあるべきものは Menu に移すようにしたいです。

2021-06-19 17:43 UTC, amotarao commented
@zeek0x 

>加えて、同じ理由で ログイン・設定 ・ 終了 も Menu に含まれているべきですね。
>Menu にあるべきものは Menu に移すようにしたいです。

メニューにもあり、トレイにもあることが多いと思います


PRの方針はオッケーだと思います。

2021-06-19 17:44 UTC, amotarao commented on src/resource.ts
> +};
このファイルの切り出しは 👍👍👍

2021-06-19 17:44 UTC, amotarao approved these changes
LGTM!

2021-06-19 17:50 UTC, zeek0x commented
issue: #133

2021-06-23 15:03 UTC, merged