feat: ログイン情報保存時に、ログイン可否を確認
TaneAkashi/DakokuApp pull request #64
Opened 2021-05-01 09:38 UTC by amotarao

fix #33

2021-05-05 11:47 UTC, zeek0x commented on src/dakoku.ts
> +      if (!win) throw new Error('別の処理が実行されています');
```suggestion
      if (win) throw new Error('別の処理が実行されています');
```

2021-05-05 11:48 UTC, zeek0x commented on src/dakoku.ts
> +  if (!win) throw new Error('別の処理が実行されています');
```suggestion
  if (win) throw new Error('別の処理が実行されています');
```

2021-05-06 15:50 UTC, zeek0x commented
win が global なせいで型エラーになってますね。
BrowserWindow 型の値はスコープを絞って、flag とかで管理すると解決しますかね？ 🤔

2021-05-06 16:29 UTC, zeek0x requested changes
win が global なせいで型エラーになってますね。
BrowserWindow 型の値はスコープを絞って、flag とかで管理すると解決しますかね？ 🤔
きちんとやる場合は lock 使ってもいいと思います。

2021-05-06 16:47 UTC, amotarao commented on src/dakoku.ts
> +let running = false;
running flag 追加

2021-05-06 16:48 UTC, amotarao commented on src/dakoku.ts
> +};
BrowserWindow を返すようにする

2021-05-06 16:48 UTC, amotarao commented on src/dakoku.ts
>  };
BrowserWindow を渡して destory させる

2021-05-06 16:49 UTC, amotarao commented
すみません、確認が適当でした。 直してみました！

2021-05-07 15:38 UTC, zeek0x approved these changes
LGTM 👍

2021-05-07 16:28 UTC, merged