アプリの自動更新通知を追加
TaneAkashi/DakokuApp pull request #71
Opened 2021-05-07 16:41 UTC by zeek0x

fix: #12

2021-05-07 16:44 UTC, zeek0x commented
7c1af06 時点ではトレイのみに表示

TODO
- [Tray] 表示の見た目を変える
- [Notification] Notification による通知を追加

2021-05-15 04:56 UTC, zeek0x commented
打刻時のほうも打刻処理をコメントアウトして動作確認した！

2021-05-15 08:35 UTC, amotarao commented on src/dakoku.ts
> +  setTimeout(release.doIfReleaseExists, 10000);
👍

2021-05-15 08:36 UTC, amotarao commented on src/release.ts
> +    });
通知クリックでリリースページ行ってもよさそうな気がしました

2021-05-15 08:41 UTC, amotarao requested changes
基本的にはよさそうです 💯 ありあとうございます。

通知クリックでリリースページ飛ばしたいのと、
アップデート後、store の release をクリアが必要かなとー！
確認いただけると嬉しいです。

2021-05-17 16:21 UTC, amotarao approved these changes
LGTM!

2021-05-17 16:21 UTC, merged